services:
  db:
    image: postgres:17
    restart: unless-stopped
    shm_size: 256mb
    volumes:
      - /mnt/data/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: cloudpoint
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cloudpoint"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  caddy:
    image: caddy:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data

  cloudpoint:
    image: dwalker109/cloudpoint
    restart: unless-stopped
    environment:
      RUST_LOG: INFO
      DATABASE_URL: postgres://postgres:postgres@db:5432/cloudpoint
    depends_on:
      db:
        condition: service_healthy

volumes:
  caddy_data:
