services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data

  db:
    image: postgres:17
    restart: unless-stopped
    shm_size: 256mb
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: cloudpoint
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cloudpoint"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  cloudpoint:
    image: dwalker109/cloudpoint:1.0.0
    restart: unless-stopped
    environment:
      RUST_LOG: INFO
      DATABASE_URL: postgres://postgres:postgres@db:5432/cloudpoint
    depends_on:
      db:
        condition: service_healthy

volumes:
  caddy_data:
  pg_data:
