services:
  db:
    image: postgres
    restart: unless-stopped
    shm_size: 256mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres

  caddy:
    image: caddy:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./Caddyfile.prod:/etc/caddy/Caddyfile
      - caddy_data:/data

volumes:
  caddy_data:
