[target.armv6k-nintendo-3ds]
linker = "/opt/devkitpro/devkitARM/bin/arm-none-eabi-gcc"

[env]
PKG_CONFIG_armv6k_nintendo_3ds             = "/opt/devkitpro/portlibs/3ds/bin/arm-none-eabi-pkg-config"
PKG_CONFIG_PATH_armv6k_nintendo_3ds        = "/opt/devkitpro/portlibs/3ds/lib/pkgconfig"
PKG_CONFIG_ALLOW_CROSS_armv6k_nintendo_3ds = "1"

CC_armv6k_nintendo_3ds = "/opt/devkitpro/devkitARM/bin/arm-none-eabi-gcc"
AR_armv6k_nintendo_3ds = "/opt/devkitpro/devkitARM/bin/arm-none-eabi-ar"

LIBZ_SYS_STATIC = "0"
Z_PREFIX_armv6k_nintendo_3ds = "/opt/devkitpro/portlibs/3ds"
