/* automatically generated by rust-bindgen 0.72.1 */

// @generated — run `just pack-img` to regenerate

pub const IMG_CLOUD: u32 = 0;
pub const IMG_DIALOG_SHADOW_BOT: u32 = 1;
pub const IMG_DIALOG_SHADOW_TOP: u32 = 2;
pub const IMG_HELP_QR: u32 = 3;
pub const IMG_LINK: u32 = 4;
pub const IMG_LIST: u32 = 5;
