/* Generated by tex3ds */
#pragma once

#define img_cloud_idx 0
#define img_dialog_shadow_bot_idx 1
#define img_dialog_shadow_top_idx 2
#define img_help_qr_idx 3
#define img_link_idx 4
#define img_list_idx 5
