/* automatically generated by rust-bindgen 0.72.1 */

// @generated — run `just pack-icons` to regenerate

pub const ICON_CLOUD: u32 = 0;
pub const ICON_DIALOG_SHADOW_BOT: u32 = 1;
pub const ICON_DIALOG_SHADOW_TOP: u32 = 2;
pub const ICON_HELP_QR: u32 = 3;
pub const ICON_LINK: u32 = 4;
pub const ICON_LIST: u32 = 5;
